"modernized" 'mm' -- w/ some simple fixes

diff --git a/wip/mm b/wip/mm
--- a/wip/mm
+++ b/wip/mm
@@ -2,30 +2,23 @@
 # mm -- more mail -- a notmuch (mail) wrapper
 
 # Created: Tue 23 Aug 2011 18:03:55 EEST (+0300) too
-# Last Modified: Tue 29 Oct 2019 23:41:27 +0200 too
+# Last Modified: Wed 27 Nov 2019 23:12:02 +0200 too
 
 # For everything in this to work, symlink this from it's repository
 # working copy position to a directory in PATH.
 
-set -eu
-
-case ~ in '~') exec >&2; echo
-	echo "Shell '/bin/sh' lacks some required modern shell functionality."
-	echo "Try 'ksh $0${1+ $*}', 'bash $0${1+ $*}'"
-	echo " or 'zsh $0${1+ $*}' instead."; echo
-	exit 1
-esac
-
 case ${BASH_VERSION-} in *.*) shopt -s xpg_echo; esac
 case ${ZSH_VERSION-} in *.*) emulate ksh; set -eu; esac
 
-warn () { echo "$@"; } >&2
-die () { echo "$@"; exit 1; } >&2
+set -euf
 
-usage () { echo "Usage: $0 $cmd" "$@"; exit 1; } >&2
+warn () { printf '%s\n' "$@"; } >&2
+die () { printf '%s\n' "$@"; exit 1; } >&2
 
-x () { echo + "$@" >&2; "$@"; }
-x_eval () { echo + "$*" >&2; eval "$*"; }
+usage () { print %s\\n "Usage: $0 $cmd $*"; exit 1; } >&2
+
+x () { printf '+ %s\n' "$*" >&2; "$@"; }
+x_exec () { printf '+ %s\n' "$*" >&2; exec "$@"; die "exec '$*' failed"; }
 
 yesno ()
 {
@@ -71,7 +64,7 @@ set_d0 ()
 }
 
 try_canon_d0 () {
-	case $d0 in */../*|*/./*)
+	case $d0 in */../* | */./* )
 		_xd0=`exec readlink -f $d0 2>/dev/null` || :
 		case $_xd0 in /*) d0=$_xd0; esac
 	esac
@@ -95,7 +88,7 @@ cmd_mua () # Launch emacs as mail user agent.
 		exec nohup setsid emacs -f notmuch >/dev/null
 		# the command above works best on linux interactive terminal
 	else
-		exec emacs --eval "(setq frame-background-mode 'dark)" -f notmuch
+		exec emacs -f notmuch
 	fi
 }
 
@@ -113,7 +106,10 @@ mbox2md5mda ()
 
 cmd_new () # Import new mail.
 {
+	#TIMEFORMAT is used by (bash) shell builtin, TIME by gnu /usr/bin/time..
 	TIMEFORMAT='%Us user %Ss system %P%% cpu %Rs total'
+	TIME='%Us user, %Ss system, %P cpu, %E total (max resident mem %Mk)'
+	export TIME
 	ymdhms=`exec date +%Y%m%d-%H%M%S`
 	case ${MAIL-} in '') # nothing to do when ''
 	;;	*"[$IFS]"*) warn "'$MAIL' contains whitespace. Ignored."
@@ -137,7 +133,7 @@ cmd_help () # emulate notmuch help by fetching pages from notmuch wiki
 	elif command -v curl >/dev/null
 	then	fcl='curl -L'
 	else
-		die no wget nor curl available
+		die 'no wget nor curl available'
 	fi
 	set -x
 	$fcl http://notmuchmail.org/manpages/notmuch-$1-1/ | \
@@ -148,7 +144,7 @@ cmd_help () # emulate notmuch help by fetching pages from notmuch wiki
 cmd_frm () # Run frm-md5mdalog.pl.
 {
 	set_d0
-	case ${1-x} in mvto:*) ;; *) exec $d0/frm-md5mdalog.pl "$@" ;; esac
+	case ${1-} in mvto:*) ;; *) exec $d0/frm-md5mdalog.pl "$@" ;; esac
 	case $# in 1) usage "mvto:path" match-re ;; esac
 	ddir=${1#*:}
 	test -d "$ddir" || die "'$ddir': no such directory"
@@ -182,20 +178,19 @@ cmd_delete () # remove emails with tag deleted
 	  in '1!')
 		x_eval 'notmuch search --output=files tag:deleted | xargs rm -v'
 		exit
-	  ;; '1h')
+	  ;; '1s')
 		x notmuch search tag:deleted
 	  ;; 0)
 		x notmuch address tag:deleted
 		echo "Append '!' to the the end of the command line to do actual deletion."
 	  ;; *)
-		usage '[!|h]'
+		usage "('!' | 's')"
 	esac
 }
 
-
 # --
 
-case ${1-} in -x) nosetx=false; shift ;; *) nosetx=true ;; esac
+case ${1-} in -x) maysetx='set -x'; shift ;; *) maysetx= ;; esac
 
 bn=${0##*/} # basename
 
@@ -223,25 +218,21 @@ cm=$1; shift
 #esac
 
 cc= cp=
-for m in `LC_ALL=C exec sed -n 's/^cmd_\([a-z0-9_]*\) (.*/\1/p' $0`
+for m in `LC_ALL=C exec sed -n 's/^cmd_\([a-z0-9_]*\) (.*/\1/p' "$0"`
 do
-	case $m in
-		$cm) cp= cc=1 cmd=$cm; break ;;
-		$cm*) cp=$cc; cc="$m $cc"; cmd=$m ;;
+	case $m in $cm) cp= cc=1 cmd=$cm; break
+		;; $cm*) cp=$cc; cc="$m $cc"; cmd=$m
 	esac
 done
 
-case $cc in '') echo ${0##*/}: $cm -- command not found.; exit 1
-esac
-case $cp in '') ;; *)
-	echo ${0##*/}: $cm -- ambiguous command: matches $cc; exit 1
-esac
-
+test   "$cc" || { echo $0: \'$cm\' -- command not found.; exit 1; }
+test ! "$cp" || { echo $0: \'$cm\' -- ambiguous command: matches $cc; exit 1; }
 unset cc cp cm
+readonly cmd
+
 #set -x
-$nosetx || set -x
-cmd_$cmd ${1+"$@"}
-exit
+$maysetx
+cmd_$cmd "$@"
 
 
 # Local variables:
